// Generated by Hive
import 'package:hive/hive.dart';

part 'vehicle.g.dart';

@HiveType(typeId: 0)
class Vehicle extends HiveObject {
  @HiveField(0)
  final String id;

  @HiveField(1)
  final String plate;

  @HiveField(2)
  final String brand;

  @HiveField(3)
  final String model;

  @HiveField(4)
  final int year;

  @HiveField(5)
  final int currentKm;

  @HiveField(6)
  final String customerId;

  Vehicle({
    required this.id,
    required this.plate,
    required this.brand,
    required this.model,
    required this.year,
    required this.currentKm,
    required this.customerId,
  });

  factory Vehicle.fromFirestore(Map<String, dynamic> data, String documentId, {String customerId = ''}) {
    return Vehicle(
      id: documentId,
      plate: data['placa'] ?? '',
      brand: data['marca'] ?? '',
      model: data['modelo'] ?? '',
      year: data['ano'] ?? 0,
      currentKm: data['km_atual'] ?? 0,
      customerId: customerId.isNotEmpty ? customerId : (data['cliente_id'] ?? ''),
    );
  }

  Map<String, dynamic> toFirestore() {
    return {
      'placa': plate,
      'marca': brand,
      'modelo': model,
      'ano': year,
      'km_atual': currentKm,
      'cliente_id': customerId,
    };
  }

  factory Vehicle.fromJson(Map<String, dynamic> json) {
    return Vehicle(
      id: json['id'] ?? '',
      plate: json['plate'] ?? '',
      brand: json['brand'] ?? '',
      model: json['model'] ?? '',
      year: json['year'] ?? 0,
      currentKm: json['currentKm'] ?? 0,
      customerId: json['customerId'] ?? '',
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'plate': plate,
      'brand': brand,
      'model': model,
      'year': year,
      'currentKm': currentKm,
      'customerId': customerId,
    };
  }
}
