// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkA_O876ZEWPal32Vdt1im5ckDNqA7Nm8',
    appId: '1:71081961038:web:f70b076b6b985200a9c51f',
    messagingSenderId: '71081961038',
    projectId: 'boost-871f2',
    authDomain: 'boost-871f2.firebaseapp.com',
    storageBucket: 'boost-871f2.firebasestorage.app',
    measurementId: 'G-N4YVHYTGYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEq_F0o9PN6Ypz1E2saHrJzG3H9r8Y1ck',
    appId: '1:71081961038:android:05da41b47e3cd3aba9c51f',
    messagingSenderId: '71081961038',
    projectId: 'boost-871f2',
    storageBucket: 'boost-871f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCvfVXG4LhrDrdtui5C3NyHoP6CquI20o',
    appId: '1:71081961038:ios:6f3060ffeda2844aa9c51f',
    messagingSenderId: '71081961038',
    projectId: 'boost-871f2',
    storageBucket: 'boost-871f2.firebasestorage.app',
    iosBundleId: 'com.example.boostPlus',
  );
}
